name: e_doctor
description: An e doctor application
version: 1.0.0+1
environment:
  sdk: ">=2.6.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  story_view: ^0.11.2
  # core firebase library
  firebase_core: 0.4.4+3
  # authentication with email and name etc
  firebase_auth: ^0.15.5+3
  # Wraps NSUserDefaults (on iOS) and SharedPreferences (on Android),
  shared_preferences: ^0.5.6+3
  # Keychain for ios aes secret for android with keyStore
  flutter_secure_storage: ^3.3.1+1
  # firebase FCM
  firebase_messaging: ^6.0.13
  # lazy load + increased scalability for classes with a listening mecanism that grows exponentially in complexity
  provider: ^4.1.0-dev+2
  # db for sync
  cloud_firestore: 0.13.4+2
  firebase_storage: ^3.1.5
  # graphql 
  graphql_flutter: 3.1.0-beta.1
  build_runner: ^1.5.2
  json_serializable: ^3.2.0
  json_annotation: ^3.0.0
  # Used for momentjs like date stuff
  jiffy: ^3.0.1
  # file picker
  # image_picker: ^0.6.4
  file_picker: ^1.6.0
  # video chat
  jitsi_meet: ^0.1.7
  # launch external urls - google maps in this case
  url_launcher: ^5.4.2
  # fetch user location
  location: ^3.0.2
  # send email from native view
  flutter_email_sender: ^3.0.1
  # play audio
  audioplayer: ^0.8.1
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/images/welcome-illustration-1.png
    - assets/images/welcome-illustration-2.png